Fix for passlib install breaking pip in Ubuntu 16.04 (#2)
* Upgrade pip using easy_install if pip is broken

python-pip on ubuntu 16.04 breaks with:
    AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Workaround: upgrade pip using easy_install

* Tweak logic for pip failure detection

* Upgrade pyopenssl

Older versions die with:
    ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'

* DRY pip upgrade logic and fix pyopenssl sooner

* Double flipped the logic there

* Update ansible_install.sh

* Update ansible_install.sh

* passlib install appears to be breaking pip

* Revert unnecessary tweaks

* Update ansible_install.sh